/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\hollow_knight_hornet.glb 
Author: DopamineWarlock (https://sketchfab.com/DopamineWarlock)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hollow-knight-hornet-afa7d15e69e14d63908b4fac653d79f6
Title: Hollow Knight Hornet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Shaw(props) {
  const { nodes, materials } = useGLTF('/models/hollow_knight_hornet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.MATERIAL_DEFAULTMATERIAL} position={[0.074, 1.026, 0.006]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.MATERIAL_DEFAULTMATERIAL} position={[0.068, 1.391, 0.056]} rotation={[0.811, 0, 0]} scale={[0.005, 0.005, 0.004]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.MATERIAL_DEFAULTMATERIAL} position={[0.065, 0.663, 0.044]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.MATERIAL_DEFAULTMATERIAL} position={[0.31, 0.609, 0.151]} rotation={[1.556, -0.026, -0.047]} scale={0.005} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[0.052, 0.07, 0.292]} rotation={[2.94, 0.026, 3.105]} scale={0.451} />
    </group>
  )
}

useGLTF.preload('/m/hollow_knight_hornet.glb')
