/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gintamaduck.glb 
Author: rocklee.ff123 (https://sketchfab.com/rocklee.ff123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elizabeth-free-fire-skin-5df5b0b4549c4285bc013a7a01619db0
Title: Elizabeth Free Fire Skin
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Duck(props) {
  const { scene } = useGLTF('/models/gintamaduck.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_85.geometry} material={materials['Material.003']} skeleton={nodes.Object_85.skeleton} />
        <skinnedMesh geometry={nodes.Object_87.geometry} material={materials.material_0} skeleton={nodes.Object_87.skeleton} />
        <skinnedMesh geometry={nodes.Object_89.geometry} material={materials['Material.001']} skeleton={nodes.Object_89.skeleton} />
        <skinnedMesh geometry={nodes.Object_90.geometry} material={materials.Material} skeleton={nodes.Object_90.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/gintamaduck.glb')
