/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 picklerick.glb 
Author: hellfa (https://sketchfab.com/hellfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retopo-rick-f673ab6508064e438f96b70502646949
Title: Retopo Rick
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pickle(props) {
  const { nodes, materials } = useGLTF('/models/picklerick.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.eye_lp} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.buziaa} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ogorek} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/picklerick.glb')
