/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 portalgun.glb 
Author: VoloshkovePole (https://sketchfab.com/VoloshkovePole)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rick-and-morty-prototype-of-portal-gun-3bd48bc193c54407a7ffdbea3c37a4d6
Title: Rick and Morty prototype of Portal Gun
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Gun(props) {
  const { nodes, materials } = useGLTF('/models/portalgun.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.flipp} scale={100} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.glass} scale={100} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.emission} scale={100} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_31.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_32.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_33.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_34.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_35.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_36.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_37.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_38.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_39.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_40.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_41.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_42.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_43.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_44.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_45.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_46.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_47.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_48.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_49.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_50.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_51.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_52.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_53.geometry} material={materials.material} scale={100} />
          <mesh geometry={nodes.defaultMaterial_54.geometry} material={materials.material} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/portalgun.glb')
