/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mer_f1.glb 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercedes-w13-concept-f1-wwwvecarzcom-1a1f8d992a3f4e2185603c87a0087781
Title: Mercedes W13 Concept F1 | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function F1_model(props) {
  const { nodes, materials } = useGLTF('/models/mer_f1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group position={[-79.728, 35.813, -152.483]} rotation={[-Math.PI / 2, 0, 0]} scale={36.026}>
          <mesh geometry={nodes.Object_8.geometry} material={materials.Body_Wings} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.BlackHole} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Details} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.BlackHole} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_22.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.BlackHole} />
        </group>
        <group position={[-76.121, 35.813, 187.647]} rotation={[-Math.PI / 2, 0, 0]} scale={[36.026, 36.026, 42.4]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.Body_Wings} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.BlackHole} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_36.geometry} material={materials.Tyre} position={[-79.73, 35.811, -152.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Tyre} position={[-76.592, 35.811, 187.647]} rotation={[-Math.PI / 2, 0, 0]} scale={[117.636, 100, 100]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Tyre} position={[79.605, 35.811, -152.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Tyre} position={[76.149, 35.811, 187.647]} rotation={[-Math.PI / 2, 0, 0]} scale={[117.636, 100, 100]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Body_Wings} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Body_Main} position={[0, 90.753, -51.273]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_54.geometry} material={materials.Body_Main} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.BlackHole} />
        </group>
        <mesh geometry={nodes.Object_59.geometry} material={materials.Body_Wings} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Body_Wings} position={[0, 90.753, 212.512]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Mirror} position={[0, 90.753, -51.983]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Body_Main} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Body_Main} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Body_Wings} position={[0, 60.041, 200.643]} rotation={[-Math.PI / 2, 0, 0]} scale={13.678} />
        <group position={[0, 61.163, -140.381]} rotation={[-Math.PI / 2, 0, 0]} scale={4.758}>
          <mesh geometry={nodes.Object_77.geometry} material={materials.Details} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.Carbon_Fiber} />
        </group>
        <mesh geometry={nodes.Object_82.geometry} material={materials.Titanium} position={[0, 60.097, -145.002]} rotation={[-Math.PI / 2, 0, 0]} scale={4.758} />
        <group position={[0, 60.097, -151.031]} rotation={[-Math.PI / 2, 0, 0]} scale={4.758}>
          <mesh geometry={nodes.Object_85.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.Details} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.Carbon_Fiber} />
        </group>
        <mesh geometry={nodes.Object_92.geometry} material={materials.Carbon_Fiber} position={[0, 38.502, -180.043]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Carbon_Fiber} position={[0, 94.442, 40.841]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group position={[9.606, 118.534, 36.104]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={133.872}>
          <mesh geometry={nodes.Object_98.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_105.geometry} material={materials.Glass} position={[0, 72.27, -67.652]} rotation={[-Math.PI / 2, 0, 0]} scale={1.817} />
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_108.geometry} material={materials.Body_Wings} />
          <mesh geometry={nodes.Object_110.geometry} material={materials.Carbon_Fiber} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_113.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.Body_Wings} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_118.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_120.geometry} material={materials.Body_Wings} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_123.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_125.geometry} material={materials.Titanium} />
        </group>
        <mesh geometry={nodes.Object_128.geometry} material={materials.Carbon_Fiber} position={[0, 47.479, 186.505]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.Carbon_Fiber} position={[0, 36.131, 186.505]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.Carbon_Fiber} position={[0, 29.115, 186.505]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.Carbon_Fiber} position={[0, 29.115, 201.858]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.Carbon_Fiber} position={[0, 47.736, -8.969]} rotation={[-Math.PI / 2, 0, 0]} scale={20.244} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.Carbon_Fiber} position={[0, 53.404, -3.189]} rotation={[-Math.PI / 2, 0, 0]} scale={16.34} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.Titanium} position={[0, 64.926, -67.687]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={8.587} />
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_149.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_151.geometry} material={materials.Carbon_Fiber} />
        </group>
        <group position={[0, 29.53, -6.456]} rotation={[-1.386, 0, 0]} scale={3.63}>
          <mesh geometry={nodes.Object_154.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.Details} />
        </group>
        <group position={[-3.225, 27.049, -9.347]} rotation={[-1.386, 0, 0.836]} scale={2.887}>
          <mesh geometry={nodes.Object_159.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_161.geometry} material={materials.Details} />
          <mesh geometry={nodes.Object_163.geometry} material={materials.Carbon_Fiber} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.465}>
          <mesh geometry={nodes.Object_166.geometry} material={materials.Details} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.Carbon_Fiber} />
        </group>
        <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_173.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_175.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_177.geometry} material={materials.Details} />
        </group>
        <group position={[22.027, 40.207, -49.275]} rotation={[-0.96, 0, 0]} scale={1.165}>
          <mesh geometry={nodes.Object_180.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.Details} />
        </group>
        <group position={[-22.21, 41.516, -51.011]} rotation={[-0.752, 0.55, -0.057]} scale={0.875}>
          <mesh geometry={nodes.Object_185.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_190.geometry} material={materials.Details} position={[-22.188, 40.04, -49.559]} rotation={[-0.845, 0.507, -0.024]} scale={0.875} />
        <mesh geometry={nodes.Object_193.geometry} material={materials.Details} position={[21.953, 41.573, -50.441]} rotation={[-0.923, -0.609, -0.073]} scale={0.875} />
        <mesh geometry={nodes.Object_196.geometry} material={materials.Carbon_Fiber} position={[0, 66.513, -59.741]} rotation={[-Math.PI / 2, 0, 0]} scale={1.394} />
        <mesh geometry={nodes.Object_199.geometry} material={materials.Carbon_Fiber} position={[0, 62.943, -59.741]} rotation={[-Math.PI / 2, 0, 0]} scale={1.394} />
        <mesh geometry={nodes.Object_202.geometry} material={materials.Details} position={[0, 64.284, -58.257]} rotation={[-Math.PI / 2, 0, 0]} scale={11.066} />
        <mesh geometry={nodes.Object_205.geometry} material={materials.Details} position={[0, 64.284, -58.287]} rotation={[-Math.PI / 2, 0, 0]} scale={11.066} />
        <mesh geometry={nodes.Object_208.geometry} material={materials.Details} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group position={[0, 60.041, 204.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_211.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_213.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.Object_216.geometry} material={materials.Titanium} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_219.geometry} material={materials.Carbon_Fiber} position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <group position={[0, 60.041, 203.409]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_222.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.Titanium} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.GlassLight} />
        </group>
        <mesh geometry={nodes.Object_229.geometry} material={materials.Details} position={[-21.771, 62.015, -48.112]} rotation={[-Math.PI / 2, 0, 0]} scale={2.517} />
        <group position={[-59.424, 51.808, 203.744]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Object_232.geometry} material={materials.Carbon_Fiber} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_236.geometry} material={materials.GlassLight} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.Titanium} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mer_f1.glb')
